name: Curie-CLI Build

on:
  push

jobs:
  docker-hub:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Step
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          #repository: navanchauhan/curie-cli
          #tag_with_ref: true
          tags: latest
          #image: navanchauhan/curie-cli
          registry: docker.io
